# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved. See /studio/LICENSE.AGPL-3.0

"""Builds one zipapp: Playwright cannot be carried, so --doctor tells the tester what to install."""

from __future__ import annotations

import shutil
import zipapp
from pathlib import Path

PKG = Path(__file__).resolve().parent
REPO = PKG.parents[2]
DEFAULT_OUT = REPO / "dist" / "studiobench.pyz"

EXCLUDE_DIRS = {"__pycache__", ".pytest_cache", "dist", "build"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo"}

MAIN = "tests.studio.studiobench.__main__:main_argv"


def _copy_package(staging: Path) -> None:
    target = staging / "tests" / "studio" / "studiobench"
    target.parent.mkdir(parents = True, exist_ok = True)
    shutil.copytree(PKG, target, ignore = shutil.ignore_patterns(*EXCLUDE_DIRS, "*.pyc", "*.pyo"))
    # tests and tests/studio are not packages in the repo but must be inside the archive.
    for pkg_dir in (staging / "tests", staging / "tests" / "studio"):
        init = pkg_dir / "__init__.py"
        if not init.exists():
            init.write_text("# generated by studiobench.build\n", encoding = "utf-8")


def _copy_robust(staging: Path) -> bool:
    """Vendored since the artifact runs with no checkout; without this file it loses its Chromium flags."""
    src = REPO / "tests" / "studio" / "_playwright_robust.py"
    if not src.exists():
        return False
    shutil.copy2(src, staging / "tests" / "studio" / "_playwright_robust.py")
    return True


def build(out: Path = DEFAULT_OUT, compressed: bool = True) -> Path:
    out = Path(out).resolve()
    out.parent.mkdir(parents = True, exist_ok = True)
    staging = out.parent / "_studiobench_staging"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents = True)

    _copy_package(staging)
    had_robust = _copy_robust(staging)

    frozen = staging / "tests" / "studio" / "studiobench" / "fixture" / "corpus" / "frozen"
    if not (frozen / "manifest.json").exists():
        raise FileNotFoundError(
            "the frozen corpus is not in the tree. Run "
            "`python -m tests.studio.studiobench.fixture.corpus --freeze` before building, or the "
            "artifact ships a benchmark with no content."
        )

    # `python foo.pyz` runs the archive-root __main__.py.
    (staging / "__main__.py").write_text(
        "import sys\n"
        "from tests.studio.studiobench.__main__ import main\n"
        "raise SystemExit(main(sys.argv[1:]))\n",
        encoding = "utf-8",
    )

    zipapp.create_archive(
        staging, target = out, interpreter = "/usr/bin/env python3", compressed = compressed
    )
    shutil.rmtree(staging)
    size_mb = out.stat().st_size / 1048576
    print(f"built {out} ({size_mb:.1f} MB)")
    if not had_robust:
        print(
            "  NOTE: _playwright_robust.py was not found, so the artifact falls back to its own "
            "Chromium flags and diagnostics"
        )
    print(f"  run it with: python {out.name} --doctor")
    return out


def _main(argv: list) -> int:
    import argparse

    ap = argparse.ArgumentParser(description = "Build the studiobench zipapp.")
    ap.add_argument("--out", default = str(DEFAULT_OUT))
    ap.add_argument("--no-compress", action = "store_true")
    args = ap.parse_args(argv)
    build(Path(args.out), compressed = not args.no_compress)
    return 0


if __name__ == "__main__":
    import sys
    raise SystemExit(_main(sys.argv[1:]))
